### ISSUE TITLE
Errors in logs if we disable the "user report" application

### ISSUE THREAD

**Issue by Akhenaton** [nextcloud/survey_client#30]
I am not absolutely sure if what you call "survey_client' is in fact the "user report" application shipped with Nextcloud 10.0. But if it is : 

Why different names ? Is it because it's the counterpart of "survey_server" ?

The "user report" application is enabled by default (contrary to what is mentioned (".../.. and you can enable/disable it at any time, **_by default it is always disabled_** )

If we disable the "user report" application, we get errors in the logs.

> Error no app in context
>     {"reqId":"1WaRggZNgD0hxCJy+5OB","remoteAddr":"2a01:cb00:a34:ec00:feaa:14ff:fe61:2a7f","app":"no app in context","message":"Exception: {\"Exception\":\"OCP\\AppFramework\\QueryException\",\"Message\":\"Could not resolve OCA\\Survey_Client\\Settings\\AdminSection! Class OCA\\Survey_Client\\Settings\\AdminSection does not exist\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/nextcloud\\/lib\\/private\\/AppFramework\\/Utility\\/SimpleContainer.php(105): OC\\AppFramework\\Utility\\SimpleContainer->resolve('OCA\\\\Survey_Clie...')\n#1 \\/var\\/www\\/nextcloud\\/lib\\/private\\/ServerContainer.php(89): OC\\AppFramework\\Utility\\SimpleContainer->query('OCA\\\\Survey_Clie...')\n#2 \\/var\\/www\\/nextcloud\\/lib\\/private\\/Settings\\/Manager.php(319): OC\\ServerContainer->query('OCA\\\\Survey_Clie...')\n#3 \\/var\\/www\\/nextcloud\\/lib\\/private\\/Settings\\/Manager.php(354): OC\\Settings\\Manager->query('OCA\\\\Survey_Clie...')\n#4 \\/var\\/www\\/nextcloud\\/settings\\/Controller\\/AdminSettingsController.php(131): OC\\Settings\\Manager->getAdminSections()\n#5 \\/var\\/www\\/nextcloud\\/settings\\/Controller\\/AdminSettingsController.php(70): OC\\Settings\\Controller\\AdminSettingsController->getNavigationParameters('server')\n#6 [internal function]: OC\\Settings\\Controller\\AdminSettingsController->index('server')\n#7 \\/var\\/www\\/nextcloud\\/lib\\/private\\/AppFramework\\/Http\\/Dispatcher.php(160): call_user_func_array(Array, Array)\n#8 \\/var\\/www\\/nextcloud\\/lib\\/private\\/AppFramework\\/Http\\/Dispatcher.php(90): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OC\\Settings\\Controller\\AdminSettingsController), 'index')\n#9 \\/var\\/www\\/nextcloud\\/lib\\/private\\/AppFramework\\/App.php(111): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OC\\Settings\\Controller\\AdminSettingsController), 'index')\n#10 \\/var\\/www\\/nextcloud\\/lib\\/private\\/AppFramework\\/Routing\\/RouteActionHandler.php(47): OC\\AppFramework\\App::main('AdminSettingsCo...', 'index', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#11 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->_invoke(Array)\n#12 \\/var\\/www\\/nextcloud\\/lib\\/private\\/Route\\/Router.php(293): calluser_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#13 \\/var\\/www\\/nextcloud\\/lib\\/base.php(967): OC\\Route\\Router->match('\\/settings\\/admin')\n#14 \\/var\\/www\\/nextcloud\\/index.php(48): OC::handleRequest()\n#15 {main}\",\"File\":\"\\/var\\/www\\/nextcloud\\/lib\\/private\\/AppFramework\\/Utility\\/SimpleContainer.php\",\"Line\":90}","level":3,"time":"2016-09-05T11:39:22+02:00","method":"GET","url":"\/index.php\/settings\/admin","user":"undisclosed"}

**Comment by Akhenaton** [comment]
Solved !

https://help.nextcloud.com/t/usage-report-0-1-5-error-in-logs-if-we-disable-this-app/2963/7?u=akhenaton
